from pathlib import Path

p=Path('orchestrator/collection_completeness.py')
text=p.read_text(encoding='utf-8')
old='''    if cfg.get("collect_attachments", True) and int(status.get("attachment_fail") or 0) > 0:\n        rows.append(row(source, "ARTIFACT", "ATTACHMENTS", "ARTIFACT_INCOMPLETE", query_state="COMPLETE", data=True,\n                        evidence=f"discovered={status.get('attachments_discovered',0)}; downloaded={status.get('attachment_ok',0)}; failed={status.get('attachment_fail',0)}",\n                        note="발견한 첨부자료 중 다운로드 실패가 있음"))\n'''
new='''    if cfg.get("collect_attachments", True):\n        attachment_rows = read_csv(root/"attachment_index.csv")\n        unresolved = [\n            r for r in attachment_rows\n            if str(r.get("collection_status") or "").upper() not in {"", "DOWNLOADED"}\n        ]\n        if unresolved:\n            by_state = defaultdict(int)\n            for r in unresolved:\n                by_state[str(r.get("collection_status") or "UNKNOWN").upper()] += 1\n            rows.append(row(\n                source, "ARTIFACT", "ATTACHMENTS", "ARTIFACT_INCOMPLETE", query_state="COMPLETE", data=True,\n                evidence=(\n                    f"discovered={status.get('attachments_discovered',len(attachment_rows))}; "\n                    f"downloaded={sum(1 for r in attachment_rows if str(r.get('collection_status') or '').upper() == 'DOWNLOADED')}; "\n                    f"unresolved={len(unresolved)}; states={dict(sorted(by_state.items()))}"\n                ),\n                note="발견한 첨부자료 중 다운로드·복구가 완료되지 않은 항목이 있음",\n            ))\n'''
assert old in text, 'ENVINFO attachment completeness block not found'
p.write_text(text.replace(old,new,1),encoding='utf-8')

t=Path('tests/test_collection_completeness.py')
s=t.read_text(encoding='utf-8')
marker='''    def test_selected_year_without_query_evidence_is_not_no_data(self):\n'''
case='''    def test_envinfo_skipped_recovery_state_is_artifact_incomplete(self):\n        with tempfile.TemporaryDirectory() as td:\n            output=Path(td); root=output/"ENVINFO"; (root/"raw_search").mkdir(parents=True)\n            (root/"raw_search"/"2024_2024_기업_p1.json").write_text("{}", encoding="utf-8")\n            write_json(root/"status.json", {\n                "status":"DATA_FOUND","rows":1,"detail_ok":1,"detail_fail":0,\n                "attachments_discovered":2,"attachment_ok":1,"attachment_fail":0,\n                "attachment_skipped_recovery_time_budget":1,\n            })\n            write_csv(root/"discovery.csv", [{"year":2024,"compId":"C1"}])\n            write_csv(root/"attachment_index.csv", [\n                {"collection_status":"DOWNLOADED","compId":"C1"},\n                {"collection_status":"SKIPPED_RECOVERY_TIME_BUDGET","compId":"C1"},\n            ])\n            rows=audit_envinfo(output,{\n                "start_year":2024,"end_year":2024,"search_terms":["기업"],\n                "search_terms_by_year":{"2024":["기업"]},"collect_details":True,"collect_attachments":True,\n            })\n            artifact=[r for r in rows if r["period_kind"]=="ARTIFACT" and r["period"]=="ATTACHMENTS"]\n            self.assertEqual(len(artifact),1)\n            self.assertEqual(artifact[0]["completeness_state"],"ARTIFACT_INCOMPLETE")\n            self.assertIn("SKIPPED_RECOVERY_TIME_BUDGET",artifact[0]["evidence"])\n\n'''
assert marker in s, 'test marker not found'
t.write_text(s.replace(marker,case+marker,1),encoding='utf-8')
