from pathlib import Path

collector = Path('collectors/corporate_docs_collect.py')
text = collector.read_text(encoding='utf-8')
old = '''DOWNLOAD_ATTEMPTS = 2\nPREFLIGHT_TIMEOUT = (5, 10)\nDOWNLOAD_TIMEOUT = (8, 25)\nATTACHMENT_DISCOVERY_TIMEOUT = (15, 30)\n'''
new = '''DOWNLOAD_ATTEMPTS = 2\nPREFLIGHT_TIMEOUT = (5, 10)\nDOWNLOAD_TIMEOUT = (8, 25)\nATTACHMENT_DISCOVERY_TIMEOUT = (15, 30)\n# requests' read timeout is an inactivity timeout, not a total transfer deadline.\n# Bound each source candidate so slow-drip servers cannot monopolize a workflow.\nMAX_DOCUMENT_WALL_SECONDS = 120.0\n'''
assert old in text
text = text.replace(old, new, 1)
old = '''def download_one(session, doc, target, total_bytes):\n    url = str(doc.get("source_url") or "")\n    headers = preflight(session, doc, url)\n    last_exc = None\n    for attempt in range(1, DOWNLOAD_ATTEMPTS + 1):\n        try:\n            with session.get(url, stream=True, timeout=DOWNLOAD_TIMEOUT, allow_redirects=True, headers=headers) as r:\n                r.raise_for_status()\n                length = int(r.headers.get("Content-Length") or 0)\n                if length and length > MAX_FILE_BYTES:\n                    raise ValueError(f"declared file size exceeds {MAX_FILE_BYTES} bytes")\n                count = 0\n                with target.open("wb") as f:\n                    for chunk in r.iter_content(1024 * 1024):\n                        if not chunk:\n                            continue\n                        count += len(chunk)\n                        if count > MAX_FILE_BYTES or total_bytes + count > MAX_TOTAL_BYTES:\n                            raise ValueError("document collection size safety limit exceeded")\n                        f.write(chunk)\n                if count == 0:\n                    raise ValueError("zero-byte document response")\n                ctype = str(r.headers.get("Content-Type") or "").split(";")[0]\n                validate_payload(doc.get("expected_extension"), ctype, target)\n                return r, count, ctype\n        except Exception as exc:\n            last_exc = exc\n            target.unlink(missing_ok=True)\n            if attempt < DOWNLOAD_ATTEMPTS:\n                time.sleep(0.5 * attempt)\n    raise last_exc\n'''
new = '''def download_one(session, doc, target, total_bytes):\n    url = str(doc.get("source_url") or "")\n    headers = preflight(session, doc, url)\n    last_exc = None\n    deadline = time.monotonic() + MAX_DOCUMENT_WALL_SECONDS\n    for attempt in range(1, DOWNLOAD_ATTEMPTS + 1):\n        remaining = deadline - time.monotonic()\n        if remaining <= 0:\n            last_exc = TimeoutError(f"document wall-clock budget exceeded ({MAX_DOCUMENT_WALL_SECONDS:.0f}s)")\n            break\n        connect_timeout = max(1.0, min(float(DOWNLOAD_TIMEOUT[0]), remaining))\n        read_timeout = max(1.0, min(float(DOWNLOAD_TIMEOUT[1]), remaining))\n        try:\n            with session.get(url, stream=True, timeout=(connect_timeout, read_timeout), allow_redirects=True, headers=headers) as r:\n                r.raise_for_status()\n                length = int(r.headers.get("Content-Length") or 0)\n                if length and length > MAX_FILE_BYTES:\n                    raise ValueError(f"declared file size exceeds {MAX_FILE_BYTES} bytes")\n                count = 0\n                with target.open("wb") as f:\n                    for chunk in r.iter_content(1024 * 1024):\n                        if time.monotonic() > deadline:\n                            raise TimeoutError(f"document wall-clock budget exceeded ({MAX_DOCUMENT_WALL_SECONDS:.0f}s)")\n                        if not chunk:\n                            continue\n                        count += len(chunk)\n                        if count > MAX_FILE_BYTES or total_bytes + count > MAX_TOTAL_BYTES:\n                            raise ValueError("document collection size safety limit exceeded")\n                        f.write(chunk)\n                if count == 0:\n                    raise ValueError("zero-byte document response")\n                ctype = str(r.headers.get("Content-Type") or "").split(";")[0]\n                validate_payload(doc.get("expected_extension"), ctype, target)\n                return r, count, ctype\n        except Exception as exc:\n            last_exc = exc\n            target.unlink(missing_ok=True)\n            if attempt < DOWNLOAD_ATTEMPTS and time.monotonic() < deadline:\n                time.sleep(min(0.5 * attempt, max(0.0, deadline - time.monotonic())))\n    raise last_exc\n'''
assert old in text
collector.write_text(text.replace(old, new, 1), encoding='utf-8')

test = Path('tests/test_corporate_docs_collect.py')
t = test.read_text(encoding='utf-8')
t = t.replace('from corporate_docs_collect import DOWNLOAD_ATTEMPTS, DOWNLOAD_TIMEOUT, PREFLIGHT_TIMEOUT, ATTACHMENT_DISCOVERY_TIMEOUT, collect', 'from corporate_docs_collect import DOWNLOAD_ATTEMPTS, DOWNLOAD_TIMEOUT, PREFLIGHT_TIMEOUT, ATTACHMENT_DISCOVERY_TIMEOUT, MAX_DOCUMENT_WALL_SECONDS, collect', 1)
t = t.replace('        self.assertLessEqual(ATTACHMENT_DISCOVERY_TIMEOUT[1],30)\n', '        self.assertLessEqual(ATTACHMENT_DISCOVERY_TIMEOUT[1],30)\n        self.assertLessEqual(MAX_DOCUMENT_WALL_SECONDS,120)\n', 1)
marker = '    def test_request_scope_mismatch_fails_closed_without_network(self):\n'
case = '''    def test_slow_drip_download_hits_total_wall_clock_budget(self):\n        with tempfile.TemporaryDirectory() as td:\n            root=Path(td); evidence=root/"docs.json"; profile=root/"profile.json"; out=root/"out"\n            profile.write_text(json.dumps({"request_id":"REQ-A","company_id":"COMP1"}),encoding="utf-8")\n            evidence.write_text(json.dumps({"schema_version":"1.0","request_id":"REQ-A","discovery_status":"COMPLETE","documents":[{"document_id":"D1","document_type":"SUSTAINABILITY_REPORT","title":"Slow report","source_url":"https://official.example/slow.pdf","expected_extension":"pdf","verification_status":"VERIFIED"}]}),encoding="utf-8")\n            session=unittest.mock.MagicMock(); session.get.return_value=FakeResponse(body=b"%PDF-slow")\n            ticks=iter([0.0, 0.0, 121.0, 121.0, 121.0])\n            with patch("corporate_docs_collect.requests.Session",return_value=session), patch("corporate_docs_collect.time.monotonic",side_effect=lambda: next(ticks)), patch("corporate_docs_collect.time.sleep"):\n                status=collect(evidence,profile,out)\n            self.assertEqual(status["downloaded"],0)\n            self.assertEqual(status["failed"],1)\n            rows=list(csv.DictReader((out/"document_index.csv").open(encoding="utf-8-sig")))\n            self.assertIn("wall-clock budget exceeded",rows[0]["notes"])\n\n'''
assert marker in t
test.write_text(t.replace(marker, case + marker, 1), encoding='utf-8')
