from pathlib import Path

# 1) ENV-INFO primary collector: stop hammering the source after the aggregate
# safety budget is first exhausted. The recovery stage owns continuation.
p = Path('collectors/envinfo_collect.py')
text = p.read_text(encoding='utf-8')
old = '    dedup={}; excluded_rows=[]; attachment_rows=[]; attachment_ok=attachment_fail=0; attachment_bytes=0\n'
new = '    dedup={}; excluded_rows=[]; attachment_rows=[]; attachment_ok=attachment_fail=0; attachment_bytes=0; attachment_budget_exhausted=False\n'
assert old in text, 'envinfo collector state init not found'
text = text.replace(old, new, 1)
old = '''                    if collect_attachments:\n                        for att in found:\n                            ok,attachment_bytes,attempts=download_attachment(s,att,attachments_root,attachment_bytes)\n                            status["requests"]+=attempts\n                            if ok: attachment_ok+=1\n                            else: attachment_fail+=1; status["errors"]+=1\n                            time.sleep(float(cfg.get("request_delay_ms",80))/1000)\n'''
new = '''                    if collect_attachments:\n                        for att in found:\n                            if attachment_budget_exhausted:\n                                att.update({\n                                    "collection_status":"DOWNLOAD_FAILED",\n                                    "error":"ValueError: attachment collection size safety limit exceeded; deferred to recovery stage",\n                                })\n                                attachment_fail+=1; status["errors"]+=1\n                                continue\n                            ok,attachment_bytes,attempts=download_attachment(s,att,attachments_root,attachment_bytes)\n                            status["requests"]+=attempts\n                            if ok:\n                                attachment_ok+=1\n                            else:\n                                attachment_fail+=1; status["errors"]+=1\n                                if "attachment collection size safety limit exceeded" in str(att.get("error") or ""):\n                                    attachment_budget_exhausted=True\n                            time.sleep(float(cfg.get("request_delay_ms",80))/1000)\n'''
assert old in text, 'envinfo attachment loop not found'
text = text.replace(old, new, 1)
old = '''            declared=int(r.headers.get("Content-Length") or 0)\n            if declared and declared>MAX_ATTACHMENT_BYTES: raise ValueError("attachment exceeds per-file safety limit")\n            target=unique_target(root/str(row["year"])/safe(row["compId"]),row["original_filename"],row["file_id"],row["file_ext"])\n'''
new = '''            declared=int(r.headers.get("Content-Length") or 0)\n            if declared and declared>MAX_ATTACHMENT_BYTES: raise ValueError("attachment exceeds per-file safety limit")\n            if declared and total_bytes+declared>MAX_ATTACHMENT_TOTAL_BYTES:\n                raise ValueError("attachment collection size safety limit exceeded")\n            target=unique_target(root/str(row["year"])/safe(row["compId"]),row["original_filename"],row["file_id"],row["file_ext"])\n'''
assert old in text, 'envinfo declared-size guard not found'
text = text.replace(old, new, 1)
old = '''        except Exception as exc:\n            last_exc=exc; total_bytes=start_total\n            try:\n                if target and target.exists(): target.unlink()\n            except Exception: pass\n            if attempt+1<max_attempts: time.sleep(0.5*(attempt+1))\n'''
new = '''        except Exception as exc:\n            last_exc=exc; total_bytes=start_total\n            try:\n                if target and target.exists(): target.unlink()\n            except Exception: pass\n            deterministic_limit = isinstance(exc, ValueError) and (\n                "attachment collection size safety limit exceeded" in str(exc)\n                or "attachment exceeds per-file safety limit" in str(exc)\n            )\n            if deterministic_limit:\n                break\n            if attempt+1<max_attempts: time.sleep(0.5*(attempt+1))\n'''
assert old in text, 'envinfo retry block not found'
text = text.replace(old, new, 1)
p.write_text(text, encoding='utf-8')

# 2) Recovery stage: make budget/time skips resumable and give recovery a
# larger, still bounded aggregate storage envelope. Multiple passes checkpoint
# after each pass and continue only when the previous pass exhausted time.
p = Path('collectors/envinfo_attachment_recovery.py')
text = p.read_text(encoding='utf-8')
old = '''TIME_BUDGET_STATUS = "SKIPPED_RECOVERY_TIME_BUDGET"\nDEFAULT_MAX_SECONDS = 360\n'''
new = '''TIME_BUDGET_STATUS = "SKIPPED_RECOVERY_TIME_BUDGET"\nTOTAL_BUDGET_STATUS = "SKIPPED_TOTAL_BUDGET"\nRETRYABLE_RECOVERY_STATES = {TIME_BUDGET_STATUS, TOTAL_BUDGET_STATUS, "DISCOVERED"}\nDEFAULT_MAX_SECONDS = 360\nDEFAULT_MAX_PASSES = 3\nDEFAULT_TOTAL_LIMIT_BYTES = 2 * 1024 * 1024 * 1024\n'''
assert old in text, 'recovery constants not found'
text = text.replace(old, new, 1)
old = '''    total_limit = int(total_limit or base.MAX_ATTACHMENT_TOTAL_BYTES)\n'''
new = '''    total_limit = DEFAULT_TOTAL_LIMIT_BYTES if total_limit is None else int(total_limit)\n'''
assert old in text, 'recovery total limit init not found'
text = text.replace(old, new, 1)
old = '''    candidates = [\n        r for r in rows\n        if r.get("collection_status") == "DOWNLOAD_FAILED"\n        and (\n            TOTAL_BUDGET_ERROR in str(r.get("error") or "")\n            or MISSING_FILE_ERROR in str(r.get("error") or "")\n        )\n    ]\n'''
new = '''    candidates = [\n        r for r in rows\n        if (\n            r.get("collection_status") in RETRYABLE_RECOVERY_STATES\n            or (\n                r.get("collection_status") == "DOWNLOAD_FAILED"\n                and (\n                    TOTAL_BUDGET_ERROR in str(r.get("error") or "")\n                    or MISSING_FILE_ERROR in str(r.get("error") or "")\n                )\n            )\n        )\n    ]\n'''
assert old in text, 'recovery candidate selection not found'
text = text.replace(old, new, 1)
text = text.replace('"collection_status": "SKIPPED_TOTAL_BUDGET",', '"collection_status": TOTAL_BUDGET_STATUS,', 1)
text = text.replace('r.get("collection_status") == "SKIPPED_TOTAL_BUDGET"', 'r.get("collection_status") == TOTAL_BUDGET_STATUS', 1)
old = '''def main():\n    ap = argparse.ArgumentParser()\n    ap.add_argument("--out", default="output/ENVINFO")\n    ap.add_argument("--repo-root", default=".")\n    ap.add_argument("--total-limit", type=int, default=base.MAX_ATTACHMENT_TOTAL_BYTES)\n    ap.add_argument("--max-seconds", type=int, default=DEFAULT_MAX_SECONDS,\n                    help="Soft wall-clock budget for recovery retries; 0 disables the limit.")\n    args = ap.parse_args()\n    recover(args.out, args.repo_root, args.total_limit, max_seconds=args.max_seconds)\n\n\nif __name__ == "__main__":\n    main()\n'''
new = '''def recover_until_settled(out_dir="output/ENVINFO", repo_root=".", total_limit=None, session=None,\n                          max_seconds=DEFAULT_MAX_SECONDS, max_passes=DEFAULT_MAX_PASSES, clock=time.monotonic):\n    """Resume bounded recovery passes until no time-budget deferrals remain.\n\n    Every pass checkpoints attachment_index before returning.  A pass is repeated only\n    when it stopped because of its wall-clock budget; aggregate-storage skips remain\n    explicit rather than causing an infinite retry loop.\n    """\n    summaries = []\n    for pass_no in range(1, max(1, int(max_passes)) + 1):\n        summary = recover(\n            out_dir, repo_root, total_limit=total_limit, session=session,\n            max_seconds=max_seconds, clock=clock,\n        )\n        summary = dict(summary)\n        summary["pass"] = pass_no\n        summaries.append(summary)\n        if int(summary.get("skipped_time_budget") or 0) == 0:\n            break\n\n    final = dict(summaries[-1]) if summaries else {}\n    final.update({\n        "passes": len(summaries),\n        "recovered_across_passes": sum(int(x.get("recovered") or 0) for x in summaries),\n        "pass_summaries": summaries,\n    })\n    _atomic_text(Path(out_dir) / "attachment_recovery_summary.json", json.dumps(final, ensure_ascii=False, indent=2))\n    print(json.dumps({\n        "recovery_passes": final.get("passes", 0),\n        "recovered_across_passes": final.get("recovered_across_passes", 0),\n        "final_attachment_ok": final.get("attachment_ok", 0),\n        "final_skipped_budget": final.get("skipped_budget", 0),\n        "final_skipped_time_budget": final.get("skipped_time_budget", 0),\n        "final_remaining_failed": final.get("remaining_failed", 0),\n    }, ensure_ascii=False))\n    return final\n\n\ndef main():\n    ap = argparse.ArgumentParser()\n    ap.add_argument("--out", default="output/ENVINFO")\n    ap.add_argument("--repo-root", default=".")\n    ap.add_argument("--total-limit", type=int, default=DEFAULT_TOTAL_LIMIT_BYTES)\n    ap.add_argument("--max-seconds", type=int, default=DEFAULT_MAX_SECONDS,\n                    help="Wall-clock budget for one recovery pass; 0 disables the limit.")\n    ap.add_argument("--max-passes", type=int, default=DEFAULT_MAX_PASSES,\n                    help="Maximum checkpointed recovery passes when time-budget deferrals remain.")\n    args = ap.parse_args()\n    recover_until_settled(\n        args.out, args.repo_root, args.total_limit,\n        max_seconds=args.max_seconds, max_passes=args.max_passes,\n    )\n\n\nif __name__ == "__main__":\n    main()\n'''
assert old in text, 'recovery main block not found'
text = text.replace(old, new, 1)
p.write_text(text, encoding='utf-8')

# 3) Regression tests: deferred states must be eligible on a later pass and the
# default recovery budget must actually exceed the primary collector budget.
p = Path('tests/test_envinfo_attachment_recovery.py')
t = p.read_text(encoding='utf-8')
marker = '''    def test_sustainability_report_is_recovered_before_supporting_evidence(self):\n'''
case = '''    def test_time_budget_deferred_row_is_resumable_on_next_pass(self):\n        with tempfile.TemporaryDirectory() as td:\n            root = Path(td); out = root / "output/ENVINFO"\n            rows = [row(file_id="F2", collection_status=recovery.TIME_BUDGET_STATUS, error="deferred")]\n            write_index(out / "attachment_index.csv", rows)\n            (out / "status.json").write_text(json.dumps({"attachment_ok": 0, "attachment_fail": 0, "errors": 0}), encoding="utf-8")\n            payload = b"resumed"\n            def fake_download(session, item, attachments_root, max_attempts=2, **kwargs):\n                target = Path(attachments_root) / "2024/C1/resumed.pdf"\n                target.parent.mkdir(parents=True, exist_ok=True); target.write_bytes(payload)\n                return target, len(payload), digest(payload), "application/pdf", 1\n            with patch.object(recovery, "download_without_total_cap", side_effect=fake_download):\n                summary = recovery.recover(out, root, total_limit=1000, max_seconds=5)\n            saved = recovery.read_rows(out / "attachment_index.csv")\n            self.assertEqual(summary["recovered"], 1)\n            self.assertEqual(saved[0]["collection_status"], "DOWNLOADED")\n\n    def test_old_total_budget_skip_is_retried_under_expanded_recovery_budget(self):\n        with tempfile.TemporaryDirectory() as td:\n            root = Path(td); out = root / "output/ENVINFO"\n            rows = [row(file_id="F2", collection_status=recovery.TOTAL_BUDGET_STATUS, error="old 500MB budget")]\n            write_index(out / "attachment_index.csv", rows)\n            (out / "status.json").write_text(json.dumps({"attachment_ok": 0, "attachment_fail": 0, "errors": 0}), encoding="utf-8")\n            payload = b"expanded-budget"\n            def fake_download(session, item, attachments_root, max_attempts=2, **kwargs):\n                target = Path(attachments_root) / "2024/C1/expanded.pdf"\n                target.parent.mkdir(parents=True, exist_ok=True); target.write_bytes(payload)\n                return target, len(payload), digest(payload), "application/pdf", 1\n            with patch.object(recovery, "download_without_total_cap", side_effect=fake_download):\n                summary = recovery.recover(out, root, total_limit=1000, max_seconds=5)\n            saved = recovery.read_rows(out / "attachment_index.csv")\n            self.assertEqual(summary["recovered"], 1)\n            self.assertEqual(saved[0]["collection_status"], "DOWNLOADED")\n\n    def test_default_recovery_budget_exceeds_primary_budget(self):\n        self.assertGreater(recovery.DEFAULT_TOTAL_LIMIT_BYTES, recovery.base.MAX_ATTACHMENT_TOTAL_BYTES)\n        self.assertGreaterEqual(recovery.DEFAULT_MAX_PASSES, 2)\n\n'''
assert marker in t, 'test insertion marker not found'
t = t.replace(marker, case + marker, 1)
p.write_text(t, encoding='utf-8')

# 4) Orchestrator cancellation and capacity controls.
p = Path('.github/workflows/collect.yml')
w = p.read_text(encoding='utf-8')
w = w.replace('''  stable_sources:\n    runs-on: ubuntu-latest\n    timeout-minutes: 45\n''', '''  stable_sources:\n    runs-on: ubuntu-latest\n    timeout-minutes: 60\n''', 1)
w = w.replace('''      - name: Upload stable sources\n        if: always()\n''', '''      - name: Upload stable sources\n        if: ${{ always() && cancelled() == false }}\n''', 1)
w = w.replace('''  package_and_validate:\n    needs: [stable_sources, icis_attempt_1, icis_attempt_2, icis_attempt_3, icis_replay]\n    if: always()\n''', '''  package_and_validate:\n    needs: [stable_sources, icis_attempt_1, icis_attempt_2, icis_attempt_3, icis_replay]\n    # A superseded request is intentionally cancelled by the concurrency group.\n    # Do not turn that cancellation into a large partial archive build.\n    if: ${{ always() && cancelled() == false }}\n''', 1)
assert 'timeout-minutes: 60' in w
assert w.count('cancelled() == false') >= 2
p.write_text(w, encoding='utf-8')
